name: Release

# on:
#   push:
#     tags:
#       - "v[0-9]+.[0-9]+.[0-9]+"

on:
  push:
    branches: [master]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [master]
    paths-ignore:
      - 'README.md'

jobs:
  push_to_hub:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Login huggingface hub
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          python -c 'from huggingface_hub import HfFolder; import os; HfFolder.save_token(os.environ["ACCESS_TOKEN"])'
      
      - name: Publish the predictor to the hub
        run: |
          python scripts/push_to_hub.py
